linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - unused
    - misspell
    - ineffassign
    - revive

linters-disable:
  - gosec

linters-settings:
  govet:
    check-shadowing: true
  revive:
    enable: true
    config: .revive.toml
  staticcheck:
    checks:
      - SA1004
      - SA5001
      - SA9003
  unused:
    check-exported: true
    check-blank: true
    check-params: true
    check-results: true
    check-types: true
    check-all: true
    test: true

run:
  tests: true
  skip-dirs-use-default: true
  skip-files: ^zz_generated\.
