version: '3.9'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - ${redis_port}:${redis_port}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${redis_password}

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${postgres_dbname}
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
    ports:
      - ${postgres_port}:${postgres_port}
  dating-app:
    build:
      context: .
    ports:
      - ${app_port}:${app_port}
    depends_on:
      - postgres
      - redis
    restart: always
    env_file: .env