version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: datingapps
    ports:
      - "5433:5432"
  dating-app:
    build:
      context: .
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    restart: always
    env_file: .env